### PR TITLE
Internal evaluation export improvements

### PR DESCRIPTION
**Pull request by mllocs**
Closes https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/issues/9

- Adds pending evaluations to the export (assigned evaluations).
- Adds "scope" and "category" columns.

### CODE REVIEW

**Comment by mllocs** [comment]
⚠️  Watch out, this is pointing to `release/0.28-stable`, I couldn't work in `main` due to incompatibilities with the "barcelona-decidim" `main` branch.

**Comment by mllocs** [comment]
@fblupi could we also deploy this one in a decidim-barcelona staging? It depends on `decidim@0.28`.

**Comment by fblupi** [comment]
@mllocs The staging instance of decidim.barcelona is already busy with this PR: https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/552

Once it's validated we will merge it and we will be able to test this one.

If you want to test both of them together, please, update the module in the PR mentioned above and ping me so I can deploy it.

**Comment by entantoencuanto** [comment]
Hi, I have created a `staging-lot2` branch which merges this PR in a version compatible with our decidim-lot2 staging platform, so the changes can be reviewed there.

cc/ @fblupi

**Comment by mllocs** [comment]
@arnaumonty ready to test it in https://decidim-lot2.populate.tools/admin

**Review by entantoencuanto — CHANGES_REQUESTED** [review]
Perfect! Only a small change, could you include the new attributes of the serializer in the test spec/services/decidim/internal_evaluation/internal_evaluation_serializer_spec.rb?

**Review by entantoencuanto — APPROVED** [review]

**Comment by fblupi** [comment]
@mllocs I've just deployed this branch in decidim-barcelona-staging

**Comment by mllocs** [comment]
pinging @NilHomedes and @arnaumonty since I'm not sure who can do the product review here. 🙏

**Comment by arnaumonty** [comment]
> pinging @NilHomedes and @arnaumonty since I'm not sure who can do the product review here. 🙏

Hi @mllocs I've been doing the export from your staging and I see two things:
- The proposal_title and proposal description is not working good. There are missing cells in the xlsx export.
- Reviewing the export we see that is better to repeat the information and not to leave empty cells in "id" and "created at" column.

**Comment by mllocs** [comment]
@arnaumonty 

> The proposal_title and proposal description is not working good. There are missing cells in the xlsx export.

Could be that the title/description translation is not available in the locale you are exporting to? I believe we take the locale from the user that is exporting. Please share the user and participatory space you used so I can reproduce it. 


> Reviewing the export we see that is better to repeat the information and not to leave empty cells in "id" and "created at" column.

What do you expect that `id` and `created at` to be in the case of an assignment? Currently, it represents the id of the `InternalEvaluation` which is only created when the valuator submits a valuation (not assigned).

**Comment by arnaumonty** [comment]
@mllocs 
> 
> > The proposal_title and proposal description is not working good. There are missing cells in the xlsx export.
> 
> Could be that the title/description translation is not available in the locale you are exporting to? I believe we take the locale from the user that is exporting. Please share the user and participatory space you used so I can reproduce it.

Yes, it could be possible one proposal was without translation in cat and Spanish, I have added content to both languages but right now I'm not succeeding exporting internal evaluations in xlsx format, something is wrong in the export and I can't check it.

The question here is how we show the information of the proposal evaluated when you have proposal information (title and description) in some languages. One solution should be adding a new column with the Id of the proposal as a new column. This facilitates the navigation in the spreadsheet later, too.

I have been testing here: https://decidim-lot2.populate.tools/admin/participatory_processes/branch-highway/components/4/manage/proposals 

> > Reviewing the export we see that is better to repeat the information and not to leave empty cells in "id" and "created at" column.
> 
> What do you expect that `id` and `created at` to be in the case of an assignment? Currently, it represents the id of the `InternalEvaluation` which is only created when the valuator submits a valuation (not assigned).

Good point. If it's like this we should leave it empty until you have the internal evaluation, and we should use title, description and proposal id fields to work with the spreadsheet after to download it and if you want to manage the data.

**Comment by mllocs** [comment]
Closing this in favor of https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/pull/12

**Pull request closed without merging**
